### ISSUE TITLE
Sophia test link failed on OS X 10.11.1

### ISSUE THREAD

**Issue by J-Liu** [pmwkaa/sophia#100]
I found sophia test link failed on OS X 10.11.1, it looks like this:

>Undefined symbols for architecture x86_64:
>  "_st_r", referenced from:
>      _ss_leb128_test0 in ss_leb128.test.o
>      _ss_pager_test0 in ss_pager.test.o
>      _ssa_malloc in ss_a.test.o
>      _ssa_realloc in ss_a.test.o
>      _ss_aslab_reuse in ss_aslab.test.o
>      _ss_order_of in ss_order.test.o
>      _ss_order_name in ss_order.test.o
>      ...
>     (maybe you meant: _st_run)
>ld: symbol(s) not found for architecture x86_64
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [sophia-test] Error 1

May you please fix it :)

**Comment by KenanSulayman** [comment]
Try running these tests in gcc?

**Comment by pmwkaa** [comment]
that's a good sign that i need to bring some CI for a Mac OS X :) i will see what i can do

**Comment by reqshark** [comment]
+1
