### ISSUE TITLE
Unaligned memory access

### ISSUE THREAD

**Issue by mejedi** [pmwkaa/sophia#101]
During Tarantool Arm port we discovered several issues with unaligned memory access in Sophia. The hardware we are using allows unaligned `int16_t` and `int32_t` but faults on unaligned `int64_t` and `float` or `double`.

Hence the patch below is by no means complete since unaligned `int16_t` and `int32_t` went unnoticed. Note: `intptr_t==int32_t` on this hardware.

https://gist.github.com/mejedi/848bd83e70bd7ec06259

**Comment by pmwkaa** [comment]
thanks
