### ISSUE TITLE
Cursors and views?

### ISSUE THREAD

**Issue by coleifer** [pmwkaa/sophia#105]
I saw that you had committed a new "Views" feature -- very cool! By chance do you have plans to add cursor support for views? I tried it on the off-chance it might work but got:

```
sp_document(view): unsupported operation
```

**Comment by pmwkaa** [comment]
yeah, it is actually supported :) we should create our documents using database which we are going to iterate, but cursor object is created against a view.

```C
void *cursor = sp_cursor(view);

void *o = sp_document(db);
while (o = sp_get(cursor, o)) {
///
}
sp_destroy(cursor);
```

**Comment by coleifer** [comment]
Thanks, worked like a charm.
