### ISSUE TITLE
Slow "get" operations?

### ISSUE THREAD

**Issue by coleifer** [pmwkaa/sophia#116]
I've written a short benchmarking script that takes a handful of ordered, embedded key-value databases and does various operations on them. I've noticed that Sophia is an order of magnitude slower when doing "get" operations for individual keys (both in order and in random order).

The way the benchmark operates is to:

1. Insert 250,000 key/value pairs of the format "00000001" -> "00000001" ... "00250000" -> "00250000".
2. Iterating from 1 to 250,000, fetch each value at the given key.
3. Iterating from 1 to 250,000 in random order, fetch each value at the given key.

I am using vanilla Sophia configuration (2.1.1) with a single string key as the index.

The times I'm getting look like this:

```
berkeleydb
Sets:         Took 1.1932
Gets:         Took 1.3449
Random Gets:  Took 2.3432
------------------------------------------------------------
kc-tree
Sets:         Took 0.384
Gets:         Took 0.5559
Random Gets:  Took 0.7486
------------------------------------------------------------
leveldb
Sets:         Took 0.5054
Gets:         Took 0.6866
Random Gets:  Took 0.9779
------------------------------------------------------------
sophia
Sets:         Took 0.7066
Gets:         Took 4.2484
Random Gets:  Took 5.6793
------------------------------------------------------------
lsm
Sets:         Took 0.967
Gets:         Took 0.6051
Random Gets:  Took 0.8536
------------------------------------------------------------
```

I should note that Sophia seems to be performing about on par with the other databases for writes and (not shown) reading **ranges** of keys, but when it comes to reading single key/value pairs it is quite slow.

Is this expected? What's going on here?

**Comment by coleifer** [comment]
I should also mention, thank you very much for your hard work on this project -- it's a very cool library. I also appreciate you re-doing the docs to make them more thorough, and for creating the engine.so website.

**Comment by pmwkaa** [comment]
thanks a lot)

These times are crazy, seems to be i've introduced some performance regression. I'll see what i can do. Can you please try to repeat this benchmark with higher number of keys? (like 10M)

**Comment by coleifer** [comment]
My code is doing roughly the following to perform a get:

```c
void *obj = sp_document(db_handle)
sp_setstring(obj, key_name, key_buffer, key_len)
sp_get(db_handle, obj)
sp_getstring(obj, 'value', &val_len)
```

I was quite surprised by the times myself. Note that fetching ranges of values is quite performant, as is setting values both in order and randomly....it's just the "get" operation that seems slow.

Are you able to verify the slowness on your end?

**Comment by pmwkaa** [comment]
Ok, i've made some quick checks (using ioarena: https://github.com/pmwkaa/ioarena)

With  **db.test.mmap = 1**:

```
<<>> sophia.set
0.1M   8.62 mb/sec
0.2M   7.87 mb/sec

[  t min,   t max]	  ops count	      %
--------------------------------------------------
[      0,       1]	     249995	 100.00 
[      2,       3]	          3	   0.00 
[      4,       5]	          1	   0.00 
[      7,       8]	          1	   0.00 
--------------------------------------------------
total:        1069 msec	     250000	   100%
min latency       : 0.002861 * 1e-3 sec/op
avg latency       : 0.004275 * 1e-3 sec/op
max latency       : 7.713079 * 1e-3 sec/op
avg throughput    : 233896 ops/sec

<<>> sophia.get
0.1M  10.93 mb/sec
0.2M  14.93 mb/sec

[  t min,   t max]	  ops count	      %
--------------------------------------------------
[      0,       1]	     250000	 100.00 
--------------------------------------------------
total:         607 msec	     250000	   100%
min latency       : 0.000000 * 1e-3 sec/op
avg latency       : 0.002430 * 1e-3 sec/op
max latency       : 0.036955 * 1e-3 sec/op
avg throughput    : 411575 ops/sec

complete.
```

With  **db.test.mmap = 0** (this is **default**: pread(2) is used):

```
<<>> sophia.set
0.1M   8.68 mb/sec
0.2M   7.58 mb/sec

[  t min,   t max]	  ops count	      %
--------------------------------------------------
[      0,       1]	     249993	 100.00 
[      2,       3]	          2	   0.00 
[      3,       4]	          2	   0.00 
[      4,       5]	          1	   0.00 
[      8,       9]	          2	   0.00 
--------------------------------------------------
total:        1088 msec	     250000	   100%
min latency       : 0.002861 * 1e-3 sec/op
avg latency       : 0.004353 * 1e-3 sec/op
max latency       : 8.513927 * 1e-3 sec/op
avg throughput    : 229714 ops/sec

<<>> sophia.get
0.1M   1.96 mb/sec
0.2M   4.49 mb/sec

[  t min,   t max]	  ops count	      %
--------------------------------------------------
[      0,       1]	     250000	 100.00 
--------------------------------------------------
total:        2886 msec	     250000	   100%
min latency       : 0.000000 * 1e-3 sec/op
avg latency       : 0.011544 * 1e-3 sec/op
max latency       : 0.087976 * 1e-3 sec/op
avg throughput    : 86625 ops/sec

complete.

```

There are significant and expected slowdown without mmap mode. So if your database is less then available RAM, i would suggest to try mmap mode.

Seems to be I need to turn it on by default :)

**Comment by coleifer** [comment]
I think the benchmark data on your site is misleading (http://sophia.systems/performance.html).

After reading more closely I see that data is for Sophia 1.2.3, but wouldn't it be more appropriate to show 2.1? Was there a significant regression for non-mmap gets between versions 1.x and 2.x? I don't think those questions are addressed and this could be very important information to potential users.

**Comment by pmwkaa** [comment]
There should be no significant regression. Both 1.2.3 and 2.1 have mmap support. The reason why there are older version because storage architecture has not changed since and good benchmark takes a lot of time and effort to make. Thanks)

**Comment by coleifer** [comment]
It's not clear to me from the performance page on the Sophia website that the get benchmark was performed with mmap=1.

**Comment by pmwkaa** [comment]
mmap was turned off.

Database performance significantly depends on data set size. This benchmark were made with large number of keys (2 billion) which were bigger than available RAM (do not remember exactly, 1:2 - 4 ratio). With this sizes it mostly does not matter whether you are using mmap or not, because its all about disk access time, pread() is slower but have a more stable latency as far as i know.
Those databases you've tried uses mmap by default (except berkley db, which i assume uses page cache). RocksDB uses pread() by default too as far as i know. Sorry for confusion.

**Comment by coleifer** [comment]
Thank you for the quick responses. I modified my benchmark to use `mmap` and got times more along the lines of what I expected:

```
                  sophia
                  Sets:  0.7424
                  Gets:  0.6328
           Random Sets:  0.8399
           Random Gets:  1.0813
                Ranges:  0.4006
```

Compare 0.6328 to 4.2484 and 1.0813 to 5.6793.

**Comment by pmwkaa** [comment]
Random Gets looks slow anyway for me. Thanks for sharing, i'll keep it in mind.
