### ISSUE TITLE
sp_getint -1 error or valid value

### ISSUE THREAD

**Issue by tencherry10** [pmwkaa/sophia#119]
Hi,

Quick question,  if sp_getint returns -1, how do you differentiate whether that is the value you are querying or whether it is an error?

Thanks,
Terry

**Comment by pmwkaa** [comment]
Hi,
Most likely the access path is incorrect (variable does not exists, and so on). In error cases **sophia.error** will be be set with error description.

**Comment by tencherry10** [comment]
Huh, so I have to check sophia.error everytime for sp_getint to make sure it isn't an error. 

It is a little counter intuitive to return error code that is also in the valid range of the output...

**Comment by pmwkaa** [comment]
Basically you right. My answer is that there are no variable which would return -1 as a result and sp_getint() should never fail, if everything is used correctly.
