### ISSUE TITLE
code organization docs

### ISSUE THREAD

**Issue by tencherry10** [pmwkaa/sophia#121]
Hi,

Is there an architecture document available that gives a bit more detailed explanation of how the source code pieces work together? I am especially interested in a decoder ring that explains the prefixes (ss_ , si_ , etc...).

Thanks,
Terry

**Comment by pmwkaa** [comment]
Not yet unfortunately, i will work to add more details about internal organzation.
First letter stands for 'sophia' and second (likely) to be first letter for library name, for example:
si_set means (sophia index _ set)

```sh
ss_ "libss.h" "std" data structures and so on
sf_ "libsf.h" "format" document format
sr_ "libsr.h" "runtime" runtime specific information
so_ "libso.h" "object" object interface and methods
sv_ "libsv.h" "version" common format-less document methods
sx_ "libsx.h" "transaction" separate in-memory transaction subsystem
sl_ "libsl.h" "log" write-ahead log
sd_ "libsd.h" "database" database storage format and methods
si_ "libsi.h" "index" sophia index and compaction
sy_ "libsy.h" "repository" repository methods
sc_ "libsc.h" "scheduler" sophia scheduler: background task planner
se_ "libse.h" "environment" sophia enveronment and main
sp_ "libsp.h" "sophia" core api calls
```

There are strict dependency graph. Lower level libraries know nothing about those who use them.
I would be glad to answer any more questions.

**Comment by tencherry10** [comment]
Hi, I was just wondering if something was readily available. If not, that is okay. Your list there is more than enough to get me going. Thanks!
