### ISSUE TITLE
limit on value size?

### ISSUE THREAD

**Issue by shadeware** [pmwkaa/sophia#122]
Hi, function ```se_document_setstring``` contains following code:
```c
	case SE_DOCUMENT_VALUE: {
		const int valuesize_max = 1 << 21;
		if (ssunlikely(size > valuesize_max)) {
			sr_error(&e->error, "value is too big (%d limit)",
			         valuesize_max);
			return -1;
		}
		v->value = pointer;
		if (ssunlikely(size == 0 && pointer))
			size = strlen(pointer);
		v->valuesize = size;
		sr_statvalue(&e->stat, size);
		break;
```
Is ```1 << 21``` conceptual limitation or it's just a sanity check/performance warning/etc? If later, it would be nice to have a way to configure this limit (at least with compille-time option).

**Comment by pmwkaa** [comment]
Hi, yes it is more for sanity check. i will add configuration options to tweak a various limits, including value limit. most likely in next release.
