### ISSUE TITLE
Custom comparator support

### ISSUE THREAD

**Issue by yinqiwen** [pmwkaa/sophia#127]
May other key/value storage engine support user defined comparator, it's useful in some scenarios.   
Is there any possible to implement this feature in sophia?  I'm just find out this feature is missing when i try to use sophia as a new backend storage engine in this project.  https://github.com/yinqiwen/ardb

**Comment by pmwkaa** [comment]
sure, i'll see what i can do.

**Comment by pmwkaa** [comment]
I've made patch for 2.2 (master, dev branch) which allows to set custom comparator:
https://github.com/pmwkaa/sophia/commit/a3d624b1f13c8bbe767678b03287e16eb8f8d259

Examples:
https://github.com/pmwkaa/sophia/blob/master/example/comparator.c
https://github.com/pmwkaa/sophia/blob/master/test/generic/scheme.test.c#L155
