### ISSUE TITLE
docs: broken link

### ISSUE THREAD

**Issue by frgm** [pmwkaa/sophia#133]
[documentation/tutorial/examples.md](https://github.com/pmwkaa/sophia/blob/59c71c7/documentation/tutorial/examples.md) has a broken link to [example/view.c](https://github.com/pmwkaa/sophia/blob/master/example/view.c).

That file was deleted by commit [cc9e384](https://github.com/pmwkaa/sophia/commit/cc9e3842c27dab3d12df98e5df7a452ab598637f#diff-6686237e4134bc96207215ed4736d429).

**Comment by pmwkaa** [comment]
yes, this feature considered obsolete in upcoming 2.2, i'll update documentation soon

**Comment by frgm** [comment]
fixed by commit [527778d](https://github.com/pmwkaa/sophia/commit/527778d2d98076035fccaf756779cc3d011835ce)
