### ISSUE TITLE
'upsert' example failure

### ISSUE THREAD

**Issue by spot62** [pmwkaa/sophia#139]
for master version:
$ ./upsert 
error: sophia/environment/se_db.c:269 upsert callback is not set

for fix: sp_setstring(env, "db.test.upsert", (char*)(intptr_t)upsert_callback, 0);
$ ./upsert 
Segmentation fault (core dumped)

for  	assert(upsert != NULL);
	assert(upsert_size != 0);

upsert: upsert.c:31: upsert_callback: Assertion `upsert_size != 0' failed.

**Comment by pmwkaa** [comment]
Thanks a lot. I've managed to miss this one somehow :(
