### ISSUE TITLE
How it is possible range scan is O(1)?

### ISSUE THREAD

**Issue by AleAntunez** [pmwkaa/sophia#144]
I was reading the documentation on the sophia.systems main webpage and found that worst case complexity for read, write and range scan was constant, but still can't figure out how its is possible a range scan can be O(1).

Anyone could solve me this question? Thanks!

**Comment by pmwkaa** [comment]
Hi, it is quite simple. The complexity is measured in terms of disk seek times.

Imagine a sorted range of keys: 0 ... 1000. Those keys represent keys stored in a database.
We can split this range into small subranges, like each subrange would have 100 keys: [0 ... 100] [100 ... 200] ... [900...1000].  Now, we can store information about those subranges in memory in format of min, max keys for every range: [0, 100], [100, 200] and so on. Also, each range should have an offset or some kind of reference to the locations of the subrange it is representing. Thats it.

Now, every time we make a lookup by key, we must find corresponding in-memory subrange reference, then read a subrange from disk and find a key in it.

**Comment by AleAntunez** [comment]
Thanks for the response! Didn't know you were measuring in terms of disk seek, i got it now!
