### ISSUE TITLE
CPU usage?

### ISSUE THREAD

**Issue by coleifer** [pmwkaa/sophia#163]
Hi @pmwkaa -- thank you for sharing this excellent library.

I have an event logging system I've been using with SQLite for some time. I thought I'd try migrating it to Sophia. The SQLite db is ~180MB, and the Sophia db is about the same.

After populating the sophia databases with the existing data, I've noticed that even when things are completely idle (no data being written or read), the sophia database is quite "busy" -- for hours it consistently is running and doing things -- even though nothing is being read or written.

Is this normal? What might be going on?

If there's anything I can do to log/debug this on my own I'd appreciate any pointers.

**Comment by pmwkaa** [comment]
Hi, do you see high CPU usage? Worker threads wake up periodically to see if there are any work to do. If there is no need to run heavy tasks (like compaction), this work should be unnoticeable and they should sleep most of the time.

**Comment by coleifer** [comment]
I wouldn't say it's "high" -- more like a steady 5-10% as reported by `top`. Since I'm running this on virtualized that has CPU quotas, I was hoping to figure out what might be causing the activity. Looking at the scheduler traces it seems like the threads are pretty much just sleeping. Maybe I need to just reduce the number of threads since the amount of work is generally pretty low.
