### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by coleifer** [pmwkaa/sophia#170]
It seems that this project is no longer being maintained.

Could you please verify this? If that's the case, please do the right thing: put a prominent warning in the README and on the project page would be helpful as well: http://sophia.systems

**Comment by hardc0d3** [comment]
Ah Dima

**Comment by pmwkaa** [comment]
Sorry folks, I am quite busy these days to find a free time.

Project is maintained any patches or bug fixes will be provided. If you need any additional help, the better way to do it is to write me directly by email. Thanks
