### ISSUE TITLE
Shared and static library symbol issue

### ISSUE THREAD

**Issue by larzconwell** [pmwkaa/sophia#39]
For some reason the compiled libraries don't have matching symbols. I'm not familiar with compiling shared and static libraries or I'd send a PR.

```
objdump -D libsophia.a | grep "<sp_recover>:" -
# Outputs the line with the sp_recover function symbol.
objdump -D libsophia.so.1.1 | grep "<sp_recover>:" -
# Nothing is outputted.
```

**Comment by pmwkaa** [comment]
i will post a link to website build section) thanks
