### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [pmwkaa/sophia#41]
I have seen that [no loop is used around a call](https://github.com/pmwkaa/sophia/blob/5031859d2a095b57a5dcfdb6082a3e410dfacb02/db/task.h#L51 "Check sp_taskwait") of the function "[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "wait on a condition")".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7 "Discussion about handling of spurious wakeups")"?

**Comment by pmwkaa** [comment]
gladly, thank you :)

**Comment by elfring** [comment]
Was any source code improved for the mentioned implementation detail?

**Comment by pmwkaa** [comment]
I've changed overall behavior of how threads are working in sophia v1.2.1 (upcoming release). Workers logic now depend on internal scheduler.
There is no need to wake a thread anymore, workers simply sleep for some time if there is no more work left to do. Even if spurious wakeup up happen for some reason (sleep timer < required), it won't be an issue for now, unless it happens too often.

**Comment by elfring** [comment]
Where can the corresponding source code be seen?

**Comment by pmwkaa** [comment]
on master branch. 

sophia/rt/sr_mutex, sr_thread.c 
sophia/sophia/so_scheduler.c

**Comment by elfring** [comment]
What will happen with the task implementation?
