### ISSUE TITLE
sophia: time-to-live support

### ISSUE THREAD

**Issue by pmwkaa** [pmwkaa/sophia#66]

**Comment by pmwkaa** [comment]
implemented by https://github.com/pmwkaa/sophia/commit/bf4d4859eb8e5f3c35fe8dba640f41be384ffb40

**Comment by KenanSulayman** [comment]
Just looking over the code it seems the keys will be accessible until they're wiped in a GC cycle, I think the keys should not be accessible after their TTL (read: appear as inexistent). What do you think?

**Comment by pmwkaa** [comment]
that is possible. this check can be easily added, even if key is being actually read.

**Comment by pmwkaa** [comment]
ok, i'll see what i can do. that make sense, thanks :)
