### ISSUE TITLE
sophia: support data compression

### ISSUE THREAD

**Issue by pmwkaa** [pmwkaa/sophia#67]

**Comment by stephenmathieson** [comment]
[snappy](https://code.google.com/p/snappy/)?

**Comment by pmwkaa** [comment]
not sure, looking at something smaller with BSD license like lz4, lzo or maybe zstd :) any thoughts?

**Comment by stephenmathieson** [comment]
zstd would be interesting.  i saw it recently, but haven't played with it yet.

**Comment by dyu** [comment]
Wow, zstd seems to offer the best of both worlds.  Hadn't seen it before.
I think lz4 and zstd (both from same author!) would be enough to handle the different use-cases.
