### ISSUE TITLE
Access to so_ctlserialize API

### ISSUE THREAD

**Issue by vitalif** [pmwkaa/sophia#70]
Hi! Sophia is stated to have wrapper-friendly API, but sp_get on ctl object is not wrapper-friendly in any way: it just returns a value of mixed type as void* pointer with no type information. So script language wrapper libraries must know about all possible call keys and do an additional check to cast the result correctly.

I see there is the so_ctlserialize function. It seems like a good solution, because its result is returned in a structure with type information.

Can you add access to this function to simplify wrapper development?

**Comment by vitalif** [comment]
Hm. Sorry. It seems I missed that all values are converted to strings...

**Comment by pmwkaa** [comment]
Sure, np. Let me know if you have any other questions.
