### ISSUE TITLE
Multiple databases in the same environment context

### ISSUE THREAD

**Issue by multimethod** [pmwkaa/sophia#76]
Hi, Dmitry!
Have a question.
```c
#include <stdio.h>
#include "sophia.h"

void x(void) {
    void *env = sp_env();
    void *ctl = sp_ctl(env);

    sp_set(ctl, "sophia.path", "./storage");

    sp_set(ctl, "db", "x");       /* "x" database */
    void *dbx = sp_get(ctl, "db.x");

    sp_open(env);

    void *o = NULL;

    char key[] = "foo";
    char val[] = "bar";
  
    o = sp_object(dbx);
    sp_set(o, "key",   key, sizeof(key));
    sp_set(o, "value", val, sizeof(val));
    sp_set(dbx, o);

    sp_destroy(env);
}

int y(void) {
    void *env = sp_env();
    void *ctl = sp_ctl(env);

    sp_set(ctl, "sophia.path", "./storage");

    sp_set(ctl, "db", "y");       /* "y" database */
    void *dby = sp_get(ctl, "db.y");

    sp_open(env);

    void *o = NULL;

    char key[] = "foo";

    o = sp_object(dby);
    sp_set(o, "key", key, sizeof(key));
    void *result = sp_get(dby, o);
    if (result) {
        char *value = sp_get(result, "value", NULL);
        printf("%s\n", value);
        sp_destroy(result);
    }

    sp_destroy(env);
}

int main(void) {
    x();
    y();
}
/* prints bar */
```
Why?
Shared logs directory between databases?
I do not understand how you can set different logs directories for different databases in the same environment context.
Is it possible to work with multiple databases in the same environment context?

Thanks.

**Comment by pmwkaa** [comment]
Hi Andrey,

Yes, it is possible to work with multiple databases. Sophia shares single log directory, thread pool, etc. under the environment. Databases don't have their own log directories, they share one.

Several databases can be involved in a multi-statement transaction. Database updates will be written as a single batch to a single log on commit.

Databases have own database directory. By default: when use set *sophia.path* new databases will be created as *sophia.path/database_name* if *db.database_name.path* is not set.

**several databases under one environment** (single statement-transactions)

```C
int xy(void) {
    void *env = sp_env();
    void *ctl = sp_ctl(env);

    sp_set(ctl, "sophia.path", "./storage"); /* storage path for both: x and y databases */

    sp_set(ctl, "db", "x");       /* "x" database */
    sp_set(ctl, "db", "y");       /* "y" database */
        
    void *dbx = sp_get(ctl, "db.x");
    void *dby = sp_get(ctl, "db.y");

    sp_open(env);

    void *o = NULL;

    char key[] = "foo";
    char val[] = "bar";

    o = sp_object(dbx);
    sp_set(o, "key",   key, sizeof(key));
    sp_set(o, "value", val, sizeof(val));
    sp_set(dbx, o); /* single statement-transaction */

    o = sp_object(dby);
    sp_set(o, "key",   key, sizeof(key));
    sp_set(o, "value", val, sizeof(val));
    sp_set(dby, o); /* single statement-transaction */

    sp_destroy(env);
}

int main(void) {
    xy();
}
```

**multi-statement transaction**

```C
int xy(void) {
    void *env = sp_env();
    void *ctl = sp_ctl(env);

    sp_set(ctl, "sophia.path", "./storage"); /* storage path for both: x and y databases */

    sp_set(ctl, "db", "x");       /* "x" database */
    sp_set(ctl, "db", "y");       /* "y" database */
        
    void *dbx = sp_get(ctl, "db.x");
    void *dby = sp_get(ctl, "db.y");

    sp_open(env);

    void *o = NULL;

    char key[] = "foo";
    char val[] = "bar";

    void *transaction = sp_begin(env); /* multi-statement transaction */

    o = sp_object(dbx);
    sp_set(o, "key",   key, sizeof(key));
    sp_set(o, "value", val, sizeof(val));
    sp_set(transaction, o); /*  use transaction object instead of database one */

    o = sp_object(dby);
    sp_set(o, "key",   key, sizeof(key));
    sp_set(o, "value", val, sizeof(val));
    sp_set(transaction, o);

    sp_commit(transaction);

    sp_destroy(env);
}

int main(void) {
    xy();
}
```

**Comment by multimethod** [comment]
Yes. I understand this functionality.
Transactions over several databases is a great thing!

But, objects ("foo"->"bar" in my example) stored in one database ("x") are read (also through the cursor) in another database ("y").
I.e. changes in one database are affected in another database. This logic confuses me.
Is it correct behavior?

**Comment by pmwkaa** [comment]
No it is not. Changes in one database should not affect anything in other databases in any case. Each database holds its own data set. Can you please tell, what was the source of this confusion? :)

**Comment by multimethod** [comment]
https://github.com/pmwkaa/sophia/issues/76#issue-69024122
In this example, I'm writing an object ("foo"->"bar") to "x" database and read same ("foo"->"bar") object from "y" database. Example prints bar.

**Comment by multimethod** [comment]
I'm doing something wrong in my example?

**Comment by pmwkaa** [comment]
Oh, that might be correct example. That is because you are reusing same sophia.path. It works like recovering db.x for db.y:

On commit records are written with special DSN (database seq number: *metric.dsn* ) which identifies a database. During log recover, records are replied to databases identified by this id.

Sophia v1.2.1-2 does not save schema information about created databases, so it must be set during configuration. This is done with an idea that an application (think another database) that uses sophia might have its own schema storage.

To resolve this situation you can set *db.y.id = 1* (db.x.id = 0). I will add schema storage in future releases, this issue will silently go away.

**Comment by multimethod** [comment]
> I will add schema storage in future releases, this issue will silently go away.

Okay. Very good. It is important.
> To resolve this situation you can set db.y.id = 1 (db.x.id = 0).

The solution seems to be ok. Thanks, Dmitry.

**Comment by pmwkaa** [comment]
I've added test case for this issues with an example how to resolve it correctly for now (configuration must contain both db.x and db.y):

https://github.com/pmwkaa/sophia/commit/10b264abc378273f3d4c481ce71e8a5d1435be80

**Comment by multimethod** [comment]
Good job!
