### ISSUE TITLE
Common Lisp binding for Sophia

### ISSUE THREAD

**Issue by multimethod** [pmwkaa/sophia#78]
Dmitry,

add link to [cl-sophia](https://github.com/multimethod/cl-sophia), please.

I will write tests in the near future.
Make a request to Quicklisp (CL package manager) after writing tests.
Advanced Sophia features will be added gradually.

Thanks.

**Comment by pmwkaa** [comment]
That looks awesome!) thanks and welcome

**Comment by multimethod** [comment]
Thanks. For good database need CL binding :)
