### ISSUE TITLE
"corrupted database repository" in sp_open

### ISSUE THREAD

**Issue by BTCDDev** [pmwkaa/sophia#86]
Hi,

I am using sophia 1.2, cross compiling from ubuntu for mingw. I am having some trouble opening a db.

sophia err (sophia/index/si_recover.c:386 corrupted database repository: DB\NXTaccts/NXTaccts)
err.-1 setting sp_open

I suspect it's an issue with si_trackdir(&track, r, i);

Matthew

**Comment by pmwkaa** [comment]
Hi,
Have you created (by yourself) or set custom directory for the database? Is it empty?
- Dmitry
