### ISSUE TITLE
Duplicate keys?

### ISSUE THREAD

**Issue by Spiritdude** [pmwkaa/sophia#87]
My use case (currently using BerkeleyDB) requires duplicate keys; as far I saw it's not (yet) supported.
a) can I "emulate" duplicate keys with sophia (1.1 or 1.2) easily?
b) any plans to support duplicate keys?

**Comment by pmwkaa** [comment]
Hi,

Yes Sophia does not support non-unique primary index at the moment. Internally index implemented as non-unique and stores transaction duplicates, which are semantically close but has different meaning.

a) Using v1.2.2 you can format key as: [key + sequence number] and then using cursor with prefix search set to iterate duplicates. Also it is possible to redefine compare function and do own key representation.

Starting from v1.2.3 (which in development) it will be possible to use multi-part keys. Probably i can define 'sequence' type too.

b) I think yes, but i can't say anything about when that happens. I assume that this task will be bound with future secondary indexes implementation.

Thanks
