### ISSUE TITLE
[Question] Binary K/V

### ISSUE THREAD

**Issue by haneefmubarak** [pmwkaa/sophia#91]
Does Sophia support the use of binary keys and/or binary values? Currently, I'm using:

```c
sp_set (object, "key", key.data, key.len);
sp_set (object, "value", value.data, value.len);
```

so I do indeed specify the length explicitly, but I was wondering if I could only put ASCII/Unicode plaintext or whether I could actually have binary data (that may contain `0x00` bytes) in either `key.data` or `value.data`.

**Comment by pmwkaa** [comment]
Hi, in v1.2.2 (which you are using) keys and values are interpret as binary data. So, data size is mandatory. In upcoming v1.2.3 i've switched to a slightly different API set, which will look like:

```c
o = sp_object(db)
sp_setstring(o, "key", "some string value", 0);
```
It will be possible to specify len or pass zero. In the zero case key will be interpret as a zero-terminated string and size calculated automatically.

**Comment by haneefmubarak** [comment]
Hey AWESOME! If it had only tolerated zero-terminated strings, I would have had to actually print numbers (as opposed to simply using `memcpy()` with an `int`. I will be able to store and retrieve things really efficiently (spatially and temporally) thanks to this!
