### ISSUE TITLE
Excessive stack usage in se_confserialize

### ISSUE THREAD

**Issue by mejedi** [pmwkaa/sophia#98]
In [se_confserialize](https://github.com/pmwkaa/sophia/blob/master/sophia/environment/se_conf.c#L824) local `conf` variable consumes 48Kb of the stack.  It breaks Tarantool ocasionally since Tarantool stacks are only 64Kb.
```C
srconf conf[1024];
```

Please remove `conf[1024]`.

Note: in older revisions the function is called `se_metaserialize`.

**Comment by pmwkaa** [comment]
thanks, valgrind helped?
