### ISSUE TITLE
Build failed on OS X 10.11.1, POSIX_FADV_DONTNEED not supported by OS X.

### ISSUE THREAD

**Issue by J-Liu** [pmwkaa/sophia#99]
I found sophia build failed on OS X 10.11.1, it looks like this:
>Jias-MacBook-Pro:sophia jia$ make
>SOPHIA v2.1.1
>cc: cc
>cflags: -DSS_INJECTION_ENABLE -g -O2 -std=c99 -pedantic -Wextra -Wall
>
>build
>cc sophia.c
>__sophia/std/ss_stdvfs.c:93:9: warning: implicit declaration of function__
>      __'posix_fadvise' is invalid in C99 [-Wimplicit-function-declaration]__
>        __return posix_fadvise(fd, off, len, POSIX_FADV_DONTNEED);__
>               ^
>**sophia/std/ss_stdvfs.c:93:37: error: use of undeclared identifier**
>      **'POSIX_FADV_DONTNEED'**
>        **return posix_fadvise(fd, off, len, POSIX_FADV_DONTNEED);**
>                                           ^
>1 warning and 1 error generated.
>make: *** [sophia.o] Error 1

Please fix it :)

**Comment by KenanSulayman** [comment]
I *just* wanted to open an issue for 10.10.2..

**Comment by pmwkaa** [comment]
thanks, hope that helps :)
